### ISSUE TITLE
Choose a place to live

### ISSUE THREAD

**Issue by pdewouters** [pdewouters/move-to-uk#2]
**_Criteria**_
- Good local secondary schools for boys and girls
- Affordable housing ( 3-4 bedroom for < 200.000 )
- Low crime rate
- Ideally small / medium city with some international community
- WordPress meetup / WordCamp
- Coworking spaces
- Good internet
- Nice to have: close to Matlock
- airport, good connections
- Renting: needs to allow pets...

**_Resources**_

http://illustreets.co.uk/explore-england/
http://www.familyinvestments.co.uk/hotspots/best-of-the-rest/top-10-cities/
http://www.telegraph.co.uk/finance/economics/11041812/Mapped-the-best-places-to-live-in-England-and-Wales.html

**_Candidates**_
- Manchester
- Sheffield
- Derby
- Nottingham
- Lincoln

**Comment by pdewouters** [comment]
Good candidates:
- Plymouth ( Eggbuckland )
- Nottingham ( Welloton, Woodthorpe )
- Derby ( Littleover )
  -Durham

**Comment by missjwo** [comment]
Brimingham

**Comment by owaincuvelier** [comment]
Good candidates:
- Bristol
- Sheffield maybe?

Bad candidates:
- Plymouth (they have a place called eggbuckland for christ sake!)

**Comment by roborourke** [comment]
Can only recommend what I know which is Liverpool maybe, especially around where I live.
- good schools
- housing in your price range round my area (suburbs around penny lane, 2m from city centre)
- 2 hours on virgin train to Euston
- Small/Medium city
- Lots of coworking spaces, some already have super fast fibre
- No WP meetup anymore, but lots of others, maker night, drone meetup, js meetup etc... Close enough to manchester for MWUG
- It's on the up&up, lots of investment, new restaurants & bars opening all the time http://www.theguardian.com/travel/liverpool

I did go to Bristol for uni and loved it there too

**Comment by pdewouters** [comment]
I'll try and visit Manchester and Liverpool, but I'm really liking Nottingham, affordable, choice of good schools, some good neighbourhoods.

**Comment by missjwo** [comment]
Nottingham is a good choice, central to the country, easy to get to locations and a nice place.

**Comment by pdewouters** [comment]
Near Sheffield: Stannington, ,beauchief, dronfield

**Comment by pdewouters** [comment]
Settled on Warrington for now
