### ISSUE TITLE
Sell car

### ISSUE THREAD

**Issue by pdewouters** [pdewouters/move-to-uk#7]
- [ ] get new registration :(
- [ ] give powers to Isabela to sell car
- [ ] get it cleaned up
- [x] put an ad on internet
- [ ] put an ad on the car itself

**Comment by pdewouters** [comment]
found a place where they'll buy for cash , same day

**Comment by pdewouters** [comment]
I can't find the registration papers, so we need to make an appointment for an inspection, pass that inspection, pay a tax, then make a new appointment to get the new papers to be able to sell the car...

**Comment by richardswain** [comment]
:clap: :dollar:
